#include "samd21_pins.h"

STATIC const mp_rom_map_elem_t board_global_dict_table[] = {
    { MP_ROM_QSTR(MP_QSTR_SDA), MP_ROM_PTR(&pin_PA00) },
    { MP_ROM_QSTR(MP_QSTR_SCL), MP_ROM_PTR(&pin_PA01) },

    { MP_ROM_QSTR(MP_QSTR_ANALOG1), MP_ROM_PTR(&pin_PA02) },
    { MP_ROM_QSTR(MP_QSTR_ANALOG2), MP_ROM_PTR(&pin_PA03) },
    { MP_ROM_QSTR(MP_QSTR_ANALOG3), MP_ROM_PTR(&pin_PB08) },
    { MP_ROM_QSTR(MP_QSTR_ANALOG4), MP_ROM_PTR(&pin_PB09) },
    { MP_ROM_QSTR(MP_QSTR_ANALOG5), MP_ROM_PTR(&pin_PA11) },
    { MP_ROM_QSTR(MP_QSTR_ANALOG6), MP_ROM_PTR(&pin_PA10) },
    { MP_ROM_QSTR(MP_QSTR_ANALOG7), MP_ROM_PTR(&pin_PA09) },
    { MP_ROM_QSTR(MP_QSTR_ANALOG8), MP_ROM_PTR(&pin_PA08) },

    { MP_ROM_QSTR(MP_QSTR_CAPTOUCH1), MP_ROM_PTR(&pin_PA04) },
    { MP_ROM_QSTR(MP_QSTR_CAPTOUCH2), MP_ROM_PTR(&pin_PA05) },
    { MP_ROM_QSTR(MP_QSTR_CAPTOUCH3), MP_ROM_PTR(&pin_PA06) },
    { MP_ROM_QSTR(MP_QSTR_CAPTOUCH4), MP_ROM_PTR(&pin_PA07) },

    { MP_ROM_QSTR(MP_QSTR_DRIVE1), MP_ROM_PTR(&pin_PB10) },
    { MP_ROM_QSTR(MP_QSTR_DRIVE2), MP_ROM_PTR(&pin_PB11) },
    { MP_ROM_QSTR(MP_QSTR_DRIVE3), MP_ROM_PTR(&pin_PA12) },
    { MP_ROM_QSTR(MP_QSTR_DRIVE4), MP_ROM_PTR(&pin_PA13) },

    { MP_ROM_QSTR(MP_QSTR_SERVO1), MP_ROM_PTR(&pin_PA14) },
    { MP_ROM_QSTR(MP_QSTR_SERVO2), MP_ROM_PTR(&pin_PA15) },
    { MP_ROM_QSTR(MP_QSTR_SERVO3), MP_ROM_PTR(&pin_PA16) },
    { MP_ROM_QSTR(MP_QSTR_SERVO4), MP_ROM_PTR(&pin_PA17) },

    { MP_ROM_QSTR(MP_QSTR_MOTOR_A1), MP_ROM_PTR(&pin_PA18) },
    { MP_ROM_QSTR(MP_QSTR_MOTOR_A2), MP_ROM_PTR(&pin_PA19) },

    { MP_ROM_QSTR(MP_QSTR_MOTOR_B1), MP_ROM_PTR(&pin_PA22) },
    { MP_ROM_QSTR(MP_QSTR_MOTOR_B2), MP_ROM_PTR(&pin_PA23) },

    { MP_ROM_QSTR(MP_QSTR_IRQ), MP_ROM_PTR(&pin_PA28) },

    { MP_ROM_QSTR(MP_QSTR_VIN_SENSE), MP_ROM_PTR(&pin_PB03) },

    { MP_ROM_QSTR(MP_QSTR_NEOPIXEL), MP_ROM_PTR(&pin_PA20) },
    { MP_ROM_QSTR(MP_QSTR_INTERNAL_NEOPIXEL), MP_ROM_PTR(&pin_PA27) },

    { MP_ROM_QSTR(MP_QSTR_LED), MP_ROM_PTR(&pin_PB22) },

};
MP_DEFINE_CONST_DICT(board_module_globals, board_global_dict_table);
